/* Bounded SD transfers over USB menu or CM0 mailbox. Generated by menutool.
 * Supply a fresh nonzero session token. Never retry an ambiguous timeout.
 * Low-level begin/read/write/finish/cancel functions are also in onewili.h.
 * C paths are absolute UTF-8 SD paths (no 1: volume prefix). Maximum file
 * size is INT32_MAX. Other menu calls may run between acknowledged chunks.
 */
#ifndef ONEWILI_FRAMED_FILES_H
#define ONEWILI_FRAMED_FILES_H
#include "onewili.h"
#include <string.h>
#include <limits.h>

static inline uint32_t ow_framed_crc(uint32_t state, const uint8_t* data, size_t n) {
    while (n--) {
        int bit;
        state ^= *data++;
        for (bit=0; bit<8; ++bit) state = (state>>1) ^ ((state&1) ? 0xedb88320u : 0);
    }
    return state;
}
static inline void ow_framed_hex(const uint8_t* data, size_t n, char* text) {
    const char* digits = "0123456789ABCDEF";
    size_t i;
    for (i=0;i<n;++i) { text[i*2]=digits[data[i]>>4]; text[i*2+1]=digits[data[i]&15]; }
    text[n*2]=0;
}
static inline int ow_framed_digit(char c) {
    return c>='0' && c<='9' ? c-'0' : c>='a' && c<='f' ? c-'a'+10 : c>='A' && c<='F' ? c-'A'+10 : -1;
}
static inline ow_status ow_framed_file_put_mem(ow_device* dev, uint32_t session,
    const char* path, const uint8_t* data, size_t len, bool overwrite) {
    char hex[385], encoded_path[255];
    int32_t acknowledged = 0;
    uint32_t returned_crc = 0, crc;
    size_t done = 0;
    ow_status status;
    if (!dev || !session || !path || path[0]!='/' || strlen(path)>127
        || (!data && len) || len>INT32_MAX) return OW_ERR_ARG;
    ow_framed_hex((const uint8_t*)path, strlen(path), encoded_path);
    crc = ~ow_framed_crc(0xffffffffu, data, len);
    status = ow_hardware_file_system_begin_file_write(dev, session, encoded_path,
        (int32_t)len, crc, overwrite, &acknowledged);
    if (status == OW_OK && acknowledged != (int32_t)len) status = OW_ERR_PROTOCOL;
    while (status == OW_OK && done < len) {
        size_t count = len-done > 192 ? 192 : len-done;
        ow_framed_hex(data+done,count,hex);
        status = ow_hardware_file_system_write_file_chunk(dev,session,(int32_t)done,hex,&acknowledged);
        if (status == OW_OK && acknowledged != (int32_t)(done+count)) status = OW_ERR_PROTOCOL;
        done += count;
    }
    if (status == OW_OK) {
        status = ow_hardware_file_system_finish_file_transfer(dev,session,&acknowledged,&returned_crc);
        if (status == OW_OK && (acknowledged != (int32_t)len || returned_crc != crc))
            status = OW_ERR_PROTOCOL;
    }
    if (status != OW_OK) (void)ow_hardware_file_system_cancel_file_transfer(dev,session);
    return status;
}
static inline ow_status ow_framed_file_get_mem(ow_device* dev, uint32_t session,
    const char* path, uint8_t* data, size_t capacity, size_t* out_len) {
    char hex[385], encoded_path[255];
    int32_t total = 0, count = 0, completed = 0;
    uint32_t crc = 0xffffffffu, returned_crc = 0;
    size_t done = 0;
    ow_status status;
    if (out_len) *out_len = 0;
    if (!dev || !session || !path || path[0]!='/' || strlen(path)>127
        || (!data && capacity) || !out_len) return OW_ERR_ARG;
    ow_framed_hex((const uint8_t*)path,strlen(path),encoded_path);
    status = ow_hardware_file_system_begin_file_read(dev,session,encoded_path,&total);
    if (status == OW_OK && total < 0) status = OW_ERR_PROTOCOL;
    if (status == OW_OK && (size_t)total > capacity) status = OW_ERR_BUFFER;
    while (status == OW_OK && done < (size_t)total) {
        const size_t wanted = (size_t)total-done > 192 ? 192 : (size_t)total-done;
        size_t i;
        status = ow_hardware_file_system_read_file_chunk(dev,session,(int32_t)done,(int32_t)wanted,&count,hex,sizeof hex);
        if (status != OW_OK) break;
        if (count != (int32_t)wanted || strlen(hex) != wanted*2) { status=OW_ERR_PROTOCOL; break; }
        for (i=0;i<wanted;++i) {
            int high=ow_framed_digit(hex[i*2]), low=ow_framed_digit(hex[i*2+1]);
            if (high<0 || low<0) { status=OW_ERR_PROTOCOL; break; }
            data[done+i]=(uint8_t)((high<<4)|low);
        }
        if (status != OW_OK) break;
        crc=ow_framed_crc(crc,data+done,wanted); done += wanted;
    }
    if (status == OW_OK) {
        status=ow_hardware_file_system_finish_file_transfer(dev,session,&completed,&returned_crc);
        if (status == OW_OK && (completed != total || returned_crc != ~crc)) status=OW_ERR_PROTOCOL;
    }
    if (status == OW_OK) *out_len=done;
    else (void)ow_hardware_file_system_cancel_file_transfer(dev,session);
    return status;
}
#endif
