#!/usr/bin/env python3
"""Generate the LabVIEW-callable C ABI from the OneWili C package.

Reads ../../c/include/onewili.h (and onewili_enums.h for the enum names) and
writes:

    include/onewili_lv_api.h    one wizard-safe prototype per device command
    src/onewili_lv_api.c        the forwarders into the real C API
    onewili_lv.def              the DLL export list (core + commands)
    docs/commands.md            VI name -> wire path -> description index

Every artefact is written with LF endings on every platform: the repo's review
model is "regenerating changes nothing", and that only holds if the output does
not depend on the host's newline convention. See labview/.gitattributes.

The generated ABI uses plain C base types only, because that is the subset
LabVIEW's Import Shared Library Wizard and Call Library Function Node handle
without ambiguity. The mapping is:

    int32_t / bool / enum / size_t  ->  int
    uint32_t                        ->  unsigned int
    uint8_t                         ->  unsigned char
    double                          ->  double
    const char*                     ->  const char*        (string in)
    const uint8_t* x, size_t x_len  ->  const unsigned char* x, int x_len
    uint8_t* x, size_t x_cap,
             size_t* x_len          ->  unsigned char* x, int x_cap, int* x_len
    char* x, size_t x_cap           ->  char* x, int x_cap  (string out)
    T* x  (scalar out)              ->  pointer to the mapped scalar; bool*
                                        becomes int* and is converted here

Run it from anywhere:  python tools/gen_lv_api.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LV = HERE.parent
ROOT = LV.parent
C_HEADER = ROOT / "c" / "include" / "onewili.h"
ENUM_HEADER = ROOT / "c" / "include" / "onewili_enums.h"

# Handled by the hand-written core (onewili_lv.c), not forwarded blindly.
SKIP = {"ow_open", "ow_close", "ow_poll_text_line"}

BANNER = """/* Generated by labview/tools/gen_lv_api.py from c/include/onewili.h.
 * Do not edit: regenerate instead. See labview/README.md.
 */
"""

# ---------------------------------------------------------------- parsing ---

DECL_RE = re.compile(r"^ow_status\s+(ow_\w+)\s*\((.*?)\)\s*;", re.M | re.S)
COMMENT_RE = re.compile(r"/\*(.*?)\*/", re.S)


def load_enums() -> set[str]:
    text = ENUM_HEADER.read_text(encoding="utf-8", errors="replace")
    return set(re.findall(r"^\}\s*(\w+);", text, re.M))


def split_params(raw: str) -> list[tuple[str, str]]:
    """['const uint8_t* data', 'size_t len'] -> [('const uint8_t*','data'), ...]"""
    out = []
    for chunk in raw.split(","):
        chunk = " ".join(chunk.split())
        if not chunk or chunk == "void":
            continue
        # the name is the last identifier; everything before it is the type
        m = re.match(r"^(.*?)([A-Za-z_]\w*)$", chunk)
        if not m:
            raise SystemExit(f"cannot parse parameter {chunk!r}")
        typ, name = m.group(1).strip(), m.group(2)
        typ = typ.replace(" *", "*").replace("* ", "*")
        out.append((typ, name))
    return out


def doc_for(text: str, decl_start: int) -> str:
    """The /* ... */ block sitting immediately above a declaration, if any."""
    head = text[:decl_start]
    end = head.rfind("*/")
    if end == -1:
        return ""
    if head[end + 2:].strip():          # something other than blank lines between
        return ""
    start = head.rfind("/*", 0, end)
    if start == -1:
        return ""
    body = head[start + 2:end]
    body = " ".join(line.strip().lstrip("*").strip() for line in body.splitlines())
    body = " ".join(body.split())
    if body.startswith("Events emitted by"):
        return ""
    return body


# ------------------------------------------------------------- type model ---

SCALAR_IN = {
    "int32_t": "int",
    "uint32_t": "unsigned int",
    "uint8_t": "unsigned char",
    "double": "double",
}
SCALAR_OUT = {
    "int32_t*": "int*",
    "uint32_t*": "unsigned int*",
    "uint8_t*": "unsigned char*",
    "double*": "double*",
}


class Arg:
    """One logical argument, in both the LabVIEW ABI and the call into C."""

    def __init__(self, kind: str, name: str, ctype: str = ""):
        self.kind = kind        # scalar_in bool_in enum_in str_in
                                # scalar_out bool_out bytes_in bytes_out str_out
        self.name = name
        self.ctype = ctype      # original C type, for casts

    def lv_params(self) -> list[str]:
        n = self.name
        if self.kind == "scalar_in":
            return [f"{SCALAR_IN[self.ctype]} {n}"]
        if self.kind in ("bool_in", "enum_in"):
            return [f"int {n}"]
        if self.kind == "str_in":
            return [f"const char* {n}"]
        if self.kind == "scalar_out":
            return [f"{SCALAR_OUT[self.ctype]} {n}"]
        if self.kind == "bool_out":
            return [f"int* {n}"]
        if self.kind == "bytes_in":
            return [f"const unsigned char* {n}", f"int {n}_len"]
        if self.kind == "bytes_out":
            return [f"unsigned char* {n}", f"int {n}_cap", f"int* {n}_len"]
        if self.kind == "str_out":
            return [f"char* {n}", f"int {n}_cap"]
        raise AssertionError(self.kind)

    def locals(self) -> list[str]:
        n = self.name
        if self.kind == "bool_out":
            return [f"    bool {n}__b = false;"]
        if self.kind == "bytes_out":
            return [f"    size_t {n}__n = 0;"]
        return []

    def call_args(self) -> list[str]:
        n = self.name
        if self.kind == "scalar_in":
            return [f"({self.ctype}){n}"]
        if self.kind == "bool_in":
            return [f"({n}) ? true : false"]
        if self.kind == "enum_in":
            return [f"({self.ctype}){n}"]
        if self.kind == "str_in":
            return [n]
        if self.kind == "scalar_out":
            return [n]
        if self.kind == "bool_out":
            return [f"&{n}__b"]
        if self.kind == "bytes_in":
            return [f"(const uint8_t*){n}", f"({n}_len > 0) ? (size_t){n}_len : (size_t)0"]
        if self.kind == "bytes_out":
            return [f"(uint8_t*){n}", f"({n}_cap > 0) ? (size_t){n}_cap : (size_t)0",
                    f"&{n}__n"]
        if self.kind == "str_out":
            return [n, f"({n}_cap > 0) ? (size_t){n}_cap : (size_t)0"]
        raise AssertionError(self.kind)

    def epilogue(self) -> list[str]:
        n = self.name
        if self.kind == "bool_out":
            return [f"    if ({n}) *{n} = {n}__b ? 1 : 0;"]
        if self.kind == "bytes_out":
            return [f"    if ({n}_len) *{n}_len = (int){n}__n;"]
        return []


def classify(params: list[tuple[str, str]], enums: set[str], fn: str) -> list[Arg]:
    args: list[Arg] = []
    i = 0
    n = len(params)
    while i < n:
        typ, name = params[i]

        nxt = params[i + 1] if i + 1 < n else None
        nxt2 = params[i + 2] if i + 2 < n else None

        # const uint8_t* x, size_t x_len   -- byte array in
        if typ == "constuint8_t*" or typ == "const uint8_t*":
            if not (nxt and nxt[0] == "size_t" and nxt[1] == name + "_len"):
                raise SystemExit(f"{fn}: unpaired byte-array input {name!r}")
            args.append(Arg("bytes_in", name))
            i += 2
            continue

        # uint8_t* x, size_t x_cap, size_t* x_len   -- byte array out
        if typ == "uint8_t*" and nxt and nxt[0] == "size_t" and nxt[1] == name + "_cap":
            if not (nxt2 and nxt2[0] == "size_t*" and nxt2[1] == name + "_len"):
                raise SystemExit(f"{fn}: byte-array output {name!r} without a length")
            args.append(Arg("bytes_out", name))
            i += 3
            continue

        # char* x, size_t x_cap   -- string out
        if typ == "char*":
            if not (nxt and nxt[0] == "size_t" and nxt[1] == name + "_cap"):
                raise SystemExit(f"{fn}: string output {name!r} without a capacity")
            args.append(Arg("str_out", name))
            i += 2
            continue

        if typ == "const char*":
            args.append(Arg("str_in", name))
        elif typ == "bool":
            args.append(Arg("bool_in", name))
        elif typ == "bool*":
            args.append(Arg("bool_out", name))
        elif typ in SCALAR_IN:
            args.append(Arg("scalar_in", name, typ))
        elif typ in SCALAR_OUT:
            args.append(Arg("scalar_out", name, typ))
        elif typ in enums:
            args.append(Arg("enum_in", name, typ))
        else:
            raise SystemExit(f"{fn}: unhandled parameter type {typ!r} ({name})")
        i += 1
    return args


# ----------------------------------------------------------------- output ---

def wrap_doc(text: str, width: int = 74) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return lines


def signature(lv_name: str, args: list[Arg]) -> str:
    params = ["int session"]
    for a in args:
        params.extend(a.lv_params())
    one = f"int {lv_name}({', '.join(params)})"
    if len(one) <= 78:
        return one
    pad = " " * (len(lv_name) + 5)
    lines, cur = [], f"int {lv_name}("
    for idx, p in enumerate(params):
        piece = p + ("," if idx + 1 < len(params) else "")
        if cur.rstrip() not in ("", f"int {lv_name}(") and \
                len(cur) + len(piece) > 78:
            lines.append(cur.rstrip())
            cur = pad
        cur += piece + " "
    lines.append(cur.rstrip())
    return "\n".join(lines) + ")"


def doc_block(doc: str, wire: str) -> list[str]:
    if not doc and not wire:
        return []
    out = []
    lines = wrap_doc(doc) if doc else []
    if wire:
        lines.append("Wire: " + wire)
    if len(lines) == 1:
        return [f"/* {lines[0]} */"]
    out.append("/* " + lines[0])
    out += [" * " + line for line in lines[1:]]
    out.append(" */")
    return out


def main() -> int:
    text = C_HEADER.read_text(encoding="utf-8", errors="replace")
    enums = load_enums()

    commands = []
    for m in DECL_RE.finditer(text):
        c_name, raw = m.group(1), m.group(2)
        if c_name in SKIP:
            continue
        params = split_params(raw)
        if not params or params[0][1] != "dev":
            raise SystemExit(f"{c_name}: first parameter is not ow_device* dev")
        if params[0][0] == "const ow_transport*":
            continue
        args = classify(params[1:], enums, c_name)
        doc = doc_for(text, m.start())
        wire = ""
        wm = re.search(r"Wire:\s*(\S+)", doc)
        if wm:
            wire = wm.group(1)
            doc = doc[:wm.start()].strip()
        commands.append({
            "c": c_name,
            "lv": "owlv_" + c_name[3:],
            "args": args,
            "doc": doc,
            "wire": wire,
        })

    if not commands:
        raise SystemExit("no commands parsed -- has onewili.h moved?")

    # ---- header ----
    h = [BANNER, "#ifndef ONEWILI_LV_API_H", "#define ONEWILI_LV_API_H", ""]
    h.append("/* %d generated device commands. Every one takes the session handle" % len(commands))
    h.append(" * first and returns an OWLV_* status; see onewili_lv.h. */")
    h.append("")
    for cmd in commands:
        h += doc_block(cmd["doc"], cmd["wire"])
        h.append(signature(cmd["lv"], cmd["args"]) + ";")
        h.append("")
    h += ["#endif /* ONEWILI_LV_API_H */", ""]

    (LV / "include" / "onewili_lv_api.h").write_text("\n".join(h), encoding="utf-8", newline="\n")

    # ---- source ----
    s = [BANNER, '#include "onewili_lv_internal.h"', ""]
    for cmd in commands:
        s.append(signature(cmd["lv"], cmd["args"]))
        s.append("{")
        s.append("    owlv_session* s = owlv__acquire(session);")
        s.append("    ow_status r;")
        for a in cmd["args"]:
            s.extend(a.locals())
        s.append("    if (!s) return OWLV_ERR_SESSION;")
        call = [f"&s->dev"]
        for a in cmd["args"]:
            call.extend(a.call_args())
        s.append(f"    r = {cmd['c']}({', '.join(call)});")
        epi = []
        for a in cmd["args"]:
            epi.extend(a.epilogue())
        if epi:
            s.append("    if (r == OW_OK) {")
            s.extend("    " + e for e in epi)
            s.append("    }")
        s.append(f'    owlv__release(s, r, "{cmd["c"]}");')
        s.append("    return (int)r;")
        s.append("}")
        s.append("")
    (LV / "src" / "onewili_lv_api.c").write_text("\n".join(s), encoding="utf-8", newline="\n")

    # ---- .def ----
    core = re.findall(r"^int (owlv_\w+)\(", (LV / "include" / "onewili_lv.h")
                      .read_text(encoding="utf-8"), re.M)
    names = list(dict.fromkeys(core + [c["lv"] for c in commands]))
    d = ["LIBRARY onewili_lv", "EXPORTS"]
    d += [f"    {n}" for n in names]
    (LV / "onewili_lv.def").write_text("\n".join(d) + "\n", encoding="utf-8", newline="\n")

    # ---- docs ----
    # Group by the wire path's menu prefix -- "i\g\t" and "i\g\s" are both the
    # GPIO menu. The manifest cannot be used for this: the Python package
    # reaches some menus by a different navigation path than the C API does
    # (BLE settings are w\b\b\* there and h\s\b\* here), so a wire-to-class
    # join silently drops a tenth of the commands.
    groups: dict[str, list] = {}
    for cmd in commands:
        prefix = cmd["wire"].rsplit("\\", 1)[0] if "\\" in cmd["wire"] else cmd["wire"]
        groups.setdefault(prefix, []).append(cmd)

    def label_for(members: list) -> str:
        """Longest shared name prefix, which is the menu path the generator
        already encoded into the function names."""
        parts = [c["lv"][len("owlv_"):].split("_") for c in members]
        common: list[str] = []
        for i in range(min(len(p) for p in parts)):
            seg = parts[0][i]
            if all(p[i] == seg for p in parts) and i < min(len(p) for p in parts) - 1:
                common.append(seg)
            else:
                break
        return "_".join(common) if common else "(root)"

    md = [
        "# OneWili LabVIEW command index",
        "",
        "Generated by `tools/gen_lv_api.py`. Do not edit.",
        "",
        f"{len(commands)} commands across {len(groups)} menus. Each row is one "
        "exported DLL function, which the Import Shared Library Wizard turns "
        "into one VI of the same name. `Wire` is the firmware menu path the "
        "command navigates to, the same string `owlv_send_raw` takes.",
        "",
    ]
    for prefix in sorted(groups, key=lambda p: (label_for(groups[p]), p)):
        members = groups[prefix]
        md += [f"## {label_for(members)}  (`{prefix}`)", "",
               "| Function | Wire | Description |", "| --- | --- | --- |"]
        for cmd in sorted(members, key=lambda c: c["lv"]):
            desc = cmd["doc"].replace("|", "\\|")
            wire = f"`{cmd['wire']}`" if cmd["wire"] else ""
            md.append(f"| `{cmd['lv']}` | {wire} | {desc} |")
        md.append("")
    (LV / "docs").mkdir(exist_ok=True)
    (LV / "docs" / "commands.md").write_text("\n".join(md), encoding="utf-8", newline="\n")

    print(f"{len(commands)} commands -> include/onewili_lv_api.h, "
          f"src/onewili_lv_api.c, onewili_lv.def, docs/commands.md")
    print(f"{len(names)} exported symbols ({len(core)} core)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
